### ISSUE TITLE
Does not currently fetch icons.

### ISSUE THREAD

**Issue by althras** [cllns/material_design_lite-rails#3]
Please add a way to bring in the icons necessary to MDL as well.

**Comment by cllns** [comment]
Great, thanks! I forgot about that.

**Comment by cllns** [comment]
@althras Can you try the instructions I've added to the README? https://github.com/cllns/material_design_lite-rails#icons

**Comment by althras** [comment]
I am already using that hack. I just assumed that there would be another way to package stuff into the assets through your gem (*= require something). There's also the roboto font embed option which can also be done with a stylesheet link.

**Comment by cllns** [comment]
Cool. That info is crucial to have on the README, so thanks for the suggestion.

As for packaging the font with this gem, I think that's outside of the scope of this gem. The `material_icons` gem seems like it's perfect for that task.

|  | Google Version | Rails Wrapper |
| --- | --- | --- |
| Material Design Lite | [`google/material-design-lite`](https://github.com/google/material-design-lite) | [`cllns/material_design_lite-rails`](https://github.com/cllns/material_design_lite-rails) |
| Material Design Icons | [`google/material-design-icons`](https://github.com/google/material-design-icons) | [`Angelmmiguel/material_icons`](https://github.com/Angelmmiguel/material_icons) |

Good call on Roboto too, I'll add an Issue for that.
