### ISSUE TITLE
Package SCSS

### ISSUE THREAD

**Issue by cllns** [cllns/material_design_lite-rails#5]
Material Design Lite can be [customized to use different colors](http://www.getmdl.io/customize/index.html).

There are:
- 19 primary colors
- 16 secondary colors

which is 304 combinations (well a bit less, since primary/secondary can't be same). That's a lot. I'm not sure if it's "too much". Seems manageable but undesirable.

Material Design Lite is written in SCSS, but compiled to, and released as, pure CSS. 
If it were a SCSS framework, we could set our own [variables](https://github.com/google/material-design-lite/blob/a3bfcf45209d1f5356fd3288cb1b1f83a1923dc2/src/_variables.scss).
We could just mirror all the SCSS in the gem, and compile it in the Rails app. That way, users could add their own `_variables.scss`, which would override the default values.

I'm not sure if that belongs in this gem. It might.

**Comment by ghost** [comment]
Why not just "install" this into the gem: https://github.com/google/material-design-lite/tree/master/src

It is the scss and so we can modify it to our liking.

**Comment by cllns** [comment]
Yup, that's the plan.

The issue I'm facing now is how to know commit of the SCSS is related to a particular compiled version.

`google/material-design-lite` uses release tags in a way I haven't seen before. They tag their releases with _only_ the compiled files (rather than in a `dist/` folder). Take a look at the [1.0.0](https://github.com/google/material-design-lite/tree/v1.0.0) tag for an example. I imagine in the commits on master there's a hint at the state of the SCSS at 1.0.0.

**Comment by cllns** [comment]
It looks like [this is the commit we want](https://github.com/google/material-design-lite/commit/0c25c12ef2641f2b129a90386d77aac8d9caf3ad). That was the last commit before the commits in v1.0.0. I wish we had a more definitive way of knowing what source is in a particular tag. I'll make an issue with them about that.

**Comment by ghost** [comment]
Oh wow. Thats kind of stupid. Did they make a tag at all?

**Comment by cllns** [comment]
I don't think so. 

Please don't call their decision "stupid" though. Remember: they're well-meaning, intelligent, hard-working people who just didn't anticipate this particular use case.

I understand the decision they made: the way it is now is much simpler. It just doesn't work for us.

**Comment by ghost** [comment]
Right. Didnt mean to offend anyone.

**Comment by ghost** [comment]
I think we should go ahead and do this, even if its hard to find.

Especially since the color purple doesnt suit my site. :P

**Comment by cllns** [comment]
I think I'll wait until they properly release them, @nahtnam.
Why not throw the SCSS files into `vendor/assets/stylesheets`, for now? 
Let me know how that goes if you do :)

**Comment by ghost** [comment]
@cllns Sorry, I gave up on MDL. Its a bit too "lite" for me :P

**Comment by cllns** [comment]
https://github.com/rubysamurai/material_design_lite-sass exists now, so I'll let them deal with the SASS and stick to providing _just_ the packaged CSS/JS.
