### ISSUE TITLE
Spinner Not Working

### ISSUE THREAD

**Issue by ghost** [cllns/material_design_lite-rails#7]
Hey!

Are you able to get the spinner working? I just cant for some reason. All it does is show the text `Loading...`.

Let me know if you are able to get it working and what code you used.

This is what I used.

``` html
<div class="mdl-spinner mdl-js-spinner is-active"></div>
```

Thanks.

**Comment by cllns** [comment]
Hm, I just tried it and it works fine for me, [locally](https://github.com/cllns/test-mdl/commit/c646518bb82e07020d2d87b67780b3e5620f5da4) and [on Heroku](http://test-mdl.herokuapp.com/).

**Comment by ghost** [comment]
Yep, you are right. This is an issue with ember.

Sorry.
