### ISSUE TITLE
JS not loading on page change

### ISSUE THREAD

**Issue by cmike444** [cllns/material_design_lite-rails#8]
I am using your gem and have followed the steps in your documentation, however I am having issues loading the javascript on a page change. It seems to only work on a hard refresh.

Do you have an idea on how to fix this?

**Comment by cllns** [comment]
Are you using turbolinks? I'd recommend disabling it, and seeing if that helps.

**Comment by cmike444** [comment]
I was hoping to avoid doing so, but I removed it and the js does load on page change now. Thank you!
